# Generated by Django 4.0.5 on 2023-08-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.CharField(max_length=25, null=True, verbose_name='标签名称'),
        ),
        migrations.AlterField(
            model_name='tagsquestion',
            name='tag',
            field=models.CharField(db_index=True, max_length=25, verbose_name='标签名称'),
        ),
    ]
