# Generated by Django 4.0.5 on 2023-08-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapplication', '0004_remove_followquestion_question_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('back_question_id', models.IntegerField(verbose_name='回帖ID')),
                ('statue', models.CharField(choices=[('upvote', '赞同'), ('zero', '未赞同不赞同'), ('downvote', '不赞同')], default='zero', max_length=10, verbose_name='赞同状态')),
            ],
            options={
                'verbose_name': '回帖用户状态表',
                'verbose_name_plural': '回帖用户状态表',
                'db_table': 'sof_back_user',
            },
        ),
        migrations.RemoveField(
            model_name='followquestion',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='followquestion',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='backquestion',
            name='downvotes',
            field=models.IntegerField(default=0, verbose_name='反对数'),
        ),
        migrations.AddField(
            model_name='backquestion',
            name='upvotes',
            field=models.IntegerField(default=0, verbose_name='赞成数'),
        ),
    ]
