# Generated by Django 4.0.5 on 2023-08-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapplication', '0006_rename_statue_backuser_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='downvotes',
            field=models.IntegerField(default=0, verbose_name='反对数'),
        ),
        migrations.AddField(
            model_name='question',
            name='upvotes',
            field=models.IntegerField(default=0, verbose_name='赞成数'),
        ),
    ]
