# Generated by Django 4.0.5 on 2023-08-30 16:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homeapplication', '0008_questionuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backquestion',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='backuser',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='followquestion',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='questionuser',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userviewquestion',
            name='user_id',
        ),
        migrations.AddField(
            model_name='backquestion',
            name='username',
            field=models.CharField(default="1", max_length=20, verbose_name='作者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backuser',
            name='username',
            field=models.CharField(default="1", max_length=20, verbose_name='作者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followquestion',
            name='username',
            field=models.CharField(default="1", max_length=20, verbose_name='作者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='username',
            field=models.CharField(default="1", max_length=20, verbose_name='作者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionuser',
            name='username',
            field=models.CharField(default="1", max_length=20, verbose_name='作者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userviewquestion',
            name='username',
            field=models.CharField(default="1", max_length=20, verbose_name='作者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='作者'),
        ),
    ]
