# Generated by Django 4.0.5 on 2023-08-30 16:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homeapplication', '0009_remove_backquestion_user_id_remove_backuser_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userimage',
            name='username',
            field=models.CharField(db_index=True, default=datetime.datetime(2023, 8, 30, 16, 54, 52, 784024, tzinfo=utc), max_length=20, unique=True, verbose_name='作者'),
            preserve_default=False,
        ),
    ]
