# Generated by Django 4.0.5 on 2023-08-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapplication', '0002_remove_question_tag_id_question_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='标题'),
        ),
    ]
