# Generated by Django 4.0.5 on 2023-08-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapplication', '0003_alter_question_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followquestion',
            name='question_id',
        ),
        migrations.AddField(
            model_name='backquestion',
            name='question_id',
            field=models.IntegerField(null=True, verbose_name='问题ID'),
        ),
        migrations.AddField(
            model_name='followquestion',
            name='back_question_id',
            field=models.IntegerField(null=True, verbose_name='回帖ID'),
        ),
    ]
