# Generated by Django 4.0.5 on 2023-08-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapplication', '0007_alter_user_managers_question_downvotes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('question_id', models.IntegerField(verbose_name='问题贴ID')),
                ('status', models.CharField(choices=[('upvote', '赞同'), ('zero', '未赞同不赞同'), ('downvote', '不赞同')], default='zero', max_length=10, verbose_name='赞同状态')),
            ],
            options={
                'verbose_name': '问题贴用户状态表',
                'verbose_name_plural': '问题贴用户状态表',
                'db_table': 'sof_question_user',
            },
        ),
    ]
